### ISSUE TITLE
Context diagrams in sol arch and VLHA gslides

### ISSUE THREAD

**Issue by philallen117** [KainosSoftwareLtd/dft-street-manager-alpha#2]
@stevenalexander 
In VLHA.gslides, I showed the promoter and authority systems that talk to our API. These are not shown in the sol arch context diagram.
But the diagram in the sol arch is in 4C visual style.
So please add to context diagram in sol arch, and I will copy  into the deck.

**Comment by stevenalexander** [comment]
Was an issue with links in sol arch, I've updated with google drive folder link here: https://drive.google.com/drive/folders/1rN2ICk93Sp8mmUJDu1EMs57X6XYcVL1B
