### ISSUE TITLE
Sol arch - Do we need to expose WMS layers publicly?

### ISSUE THREAD

**Issue by philallen117** [KainosSoftwareLtd/dft-street-manager-alpha#3]
@stevenalexander - Do we need to expose WMS (and WFS) layers publicly?
Public net - yes.
Call to WMS/WFS could be from client-side tool. Unlike for RESTful APIs, which will always be server with a cert (and TBD white-listed IP address)
We need a scenario about securing calls to WMS/WFS.

**Comment by stevenalexander** [comment]
I've put detail in Sol arch
